exclude: 'docs|node_modules|migrations|.git|.tox'
default_stages: [commit]
fail_fast: true

repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6
      args: [--skip-string-normalization]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
    - id: flake8
    - id: check-merge-conflict
    - id: end-of-file-fixer
    - id: debug-statements
    - id: name-tests-test
    - id: check-docstring-first
    - id: trailing-whitespace

-   repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]
